server:
  port: 8002

# Database connection properties
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/LMSATTENDANCESERVICE
    url: jdbc:mysql://${MYSQL_HOST:mysql-service}:3306/LMSATTENDANCESERVICE
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#  servlet:
#    context-path: /lms-attendance-service
#spring:
#  application:
#    name: lms-attendance-service
#  profiles:
#    active: default
#  datasource:
#    url: jdbc:mysql://localhost:3306/LMSATTENDANCESERVICE
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/LMSATTENDANCESERVICE
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    hibernate:
#      ddl-auto: update
#      show-sql: true
#  config:
#    import: optional:configserver:http://localhost:5555
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/Lms-attendance-microservices
#          jwk-set-uri: http://localhost:8080/realms/lms/protocol/openid-connect/certs
management:
  endpoints:
    web:
      exposure:
        include: "*"

